# Notice the v1beta3 version
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
# some metadata about the template itself
metadata:
  name: amorphie-software-template-for-azure
  title: Amorphie Software Template to Publish Azure Repo
  description: amorphie altyapisini kullanacak servisler icin hazırlanan template
spec:
  owner: integration
  type: service

  # these are the steps which are rendered in the frontend with the form input
  parameters:
    - title: Fill in some steps
      required:
        - name
        - projectName
        - tfsHost
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the component
          ui:autofocus: true
          ui:options:
            rows: 5
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
        projectName:
          title: projectName
          type: string
          description: write tfs project name
          ui:autofocus: true
          ui:options:
            rows: 5
        tfsHost:
          title: tfsHost
          type: string
          description: allowed host for tfs
          ui:autofocus: true
          ui:options:
            rows: 5
    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts: ${{ parameters.tfsHost }}
            allowedOrganizations: 
              - DefaultCollection
            allowedProjects: ${{ parameters.projectName }}
            
    - title: Authentication Token for target repo
      required:
        - token
      properties:
        token:
          title: Token
          type: string
          description: Unique name of the component
          ui:autofocus: true
          ui:options:
            rows: 5
  # here's the steps that are executed in series in the scaffolder backend
  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:plain
      input:
        url: ./
    - id: delete-files
      name: Delete files
      action: fs:delete
      input:
        files:
          - .deepsource.toml
          - .github
          - backstage-template.yaml
          - backstage-template-azure.yaml
    - id: publish
      name: Publish
      action: publish:azure
      input:
        description: This is ${{ parameters.name }}
        repoUrl: ${{ parameters.repoUrl }}
        token: ${{ parameters.token }}
        defaultBranch: master
  # some outputs which are saved along with the job for use in the frontend
  output:
    links:
      - title: Repository
        url: ${{ steps['publish'].output.remoteUrl }}
