version: "3.9"
services:

  redis:
    extends:
      file: services/redis.yaml
      service: redis

  redisinsight:
    extends:
      file: services/redisinsight.yaml
      service: redisinsight
         
  zeebe:
    extends:
      file: services/zeebe.yaml
      service: zeebe
      
  operate:
    extends:
      file: services/operate.yaml
      service: operate

  postgres:
    extends:
      file: services/postgres.yaml
      service: postgres

  pgadmin:
    extends:
      file: services/pgadmin.yaml
      service: pgadmin

  elastic:
    extends:
      file: services/elastic.yaml
      service: elastic
  
  kibana:
    extends:
      file: services/kibana.yaml
      service: kibana

  vault:
    extends:
      file: services/vault.yaml
      service: vault
      
  vault-prepopulate:
    extends:
      file: services/vault-prepopulate.yaml
      service: vault-prepopulate

  zipkin:
    extends:
      file: services/zipkin.yaml
      service: zipkin

  prometheus:
    extends:
      file: services/prometheus.yaml
      service: prometheus

  grafana:
    extends:
      file: services/grafana.yaml
      service: grafana
        
        
  zookeeper:
    extends:
      file: services/zookeeper.yaml
      service: zookeeper
  
  kafka:
    extends:
      file: services/kafka.yaml
      service: kafka
      
      
  kafka-ui:
    extends:
      file: services/kafka-ui.yaml
      service: kafka-ui

  kafka-connect:
    extends:
      file: services/kafka-connect.yaml
      service: kafka-connect
    
  placement:
    extends:
      file: services/placement.yaml
      service: placement

networks:
  bbt-development:
    external: true

volumes:
  redis:
  redisinsight:
  postgres:
  pgadmin:
  dapr:
  grafana-data:
  prometheus:
  zookeeper:
  kafka:
  kafka-ui:
  kafka-connect:

