version: "3.9"
services:
  grafana:
    container_name: bbt-template-grafana
    image: grafana/grafana:latest
    volumes:
      - ../grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - grafana-data:/var/lib/grafana
    
    ports:
      - "3000:3000"
    networks:
      - bbt-development
    depends_on:
      - prometheus