version: "3.9"
services:
  kafka:
    image: confluentinc/cp-kafka
    container_name: bbt-template-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zbbt-template-ookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://bbt-template-kafka:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_LOG_DIRS=/var/lib/kafka/data