version: "3.9"
services:
  kibana:
    container_name: bbt-template-kibana
    image: kibana:8.8.1
    environment:
      - ELASTICSEARCH_HOSTS=http://bbt-template-elastic:9200
    networks:
      - bbt-development
    depends_on:
      - elastic
    ports:
      - 5601:5601