version: "3.9"
services:
  prometheus:
    container_name: bbt-template-prometheus
    image: prom/prometheus:latest
    command:
      - "--config.file=/etc/prometheus.yml"
    volumes:
      - ./prometheus:/etc
    ports:
      - "9090:9090"
    networks:
      - bbt-development