version: "3.9"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: bbt-template-zookeeper
    ports:
      - "2181:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000